# -*- coding: utf-8 -*-
"""PINN Utilities (with Save Option)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hU6JziWcttB5Y7eMMcOxOr6Vz1dHfXl5
"""

# -*- coding: utf-8 -*-
"""
Utility functions for the Physics-Informed Neural Network (PINN)
stock forecasting model. This includes functions for creating
convolutional kernels and for plotting results and loss history.

MODIFICATION: The plotting function has been updated to remove the
forecast uncertainty cone. Plotting functions now support saving
figures to a file.
"""
import torch
import numpy as np
import matplotlib.pyplot as plt

def create_strided_kernel(size, stride):
    """
    Creates a 1D PyTorch convolution kernel for a strided moving average.
    """
    kernel_tensor = torch.zeros(size)
    kernel_tensor[::stride] = 1
    return (kernel_tensor / kernel_tensor.sum()).view(1, 1, -1)

def create_gaussian_kernel(size, std):
    """
    Creates a 1D PyTorch convolution kernel with Gaussian weights.
    """
    t = np.linspace(-size // 2, size // 2, size)
    gauss = np.exp(-0.5 * (t / std) ** 2)
    kernel = torch.tensor(gauss, dtype=torch.float32)
    return (kernel / kernel.sum()).view(1, 1, -1)

def plot_forecast_results(df_train, df_test, p_train, p_test, p_train_pred, forecast, save_path=None):
    """
    Plots the training fit and the forecast.

    Args:
        df_train (pd.DataFrame): DataFrame containing the training data index.
        df_test (pd.DataFrame): DataFrame containing the test data index.
        p_train (np.array): The actual training price data.
        p_test (np.array): The actual test price data.
        p_train_pred (np.array): The model's prediction on the training data.
        forecast (np.array): The forecast predictions on test data.
        save_path (str, optional): If provided, saves the plot to this path.
                                   Otherwise, shows the plot. Defaults to None.
    """
    plt.figure(figsize=(15, 8))

    # Plot training data and fit
    plt.plot(df_train.index, p_train, label="Training Data (Actual)", color="black")
    plt.plot(df_train.index, p_train_pred, label="Model Fit on Training Data", color="blue", linestyle="--")

    # Plot testing data
    plt.plot(df_test.index, p_test, label="Test Data (Actual)", color="green")

    # Plot forecast
    plt.plot(df_test.index, forecast, label="Forecast", color="red", linestyle="--")

    plt.title("Stock Price Forecast")
    plt.xlabel("Date")
    plt.ylabel("Smoothed Price")
    plt.legend()
    plt.grid(True)

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.close() # Close the plot to free up memory and prevent display
    else:
        plt.show()

def plot_loss(epochs, trainer, save_path=None):
    """
    Plots the complete training loss history over epochs.

    Args:
        epochs (int): The total number of training epochs.
        trainer (PINNTrainer): The trainer object containing loss histories.
        save_path (str, optional): If provided, saves the plot to this path.
                                   Otherwise, shows the plot. Defaults to None.
    """
    plt.figure(figsize=(12, 6))
    plt.plot(range(epochs), trainer.loss_history, label='Total Loss')
    plt.plot(range(epochs), trainer.data_loss_history, label='Data (MSE) Loss', linestyle=':')
    plt.plot(range(epochs), trainer.pde_loss_history, label='P(t) PDE Loss', linestyle=':')
    for name, history in trainer.temporal_losses_history.items():
        plt.plot(range(epochs), history, label=f'{name} PDE Loss', linestyle=':')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Training Loss Over Time')
    plt.yscale('log')
    plt.legend()
    plt.grid(True)

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.close() # Close the plot to free up memory and prevent display
    else:
        plt.show()