# -*- coding: utf-8 -*-
"""report_generator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1btOT5sAbuFfGm4nrhadv0pxtmD8ss38A
"""

# -*- coding: utf-8 -*-
"""
Utility function to generate a LaTeX report and zip output files from a PINN run.
"""
import os
from datetime import datetime
import zipfile

def generate_latex_report(report_filename, log_filename, forecast_plot_filename, loss_plot_filename, final_params, config):
    """
    Generates a LaTeX (.tex) file summarizing the results of a PINN run.

    Args:
        report_filename (str): Path to save the output .tex file.
        log_filename (str): Path to the log file for the run.
        forecast_plot_filename (str): Path to the saved forecast plot image.
        loss_plot_filename (str): Path to the saved loss plot image.
        final_params (dict): Dictionary of the final learned parameter values.
        config (dict): Dictionary of key configuration parameters for the run.
    """
    # Read the full log file content
    try:
        with open(log_filename, 'r', encoding='utf-8') as f:
            log_content = f.read()
    except Exception as e:
        log_content = f"Could not read log file: {e}"

    # Format parameters and config into LaTeX table rows
    params_rows = ""
    for key, value in final_params.items():
        key_latex = str(key).replace('_', '\\_')
        params_rows += f"\\textbf{{{key_latex}}} & {value:.6f} \\\\\\\\ \n"

    config_rows = ""
    for key, value in config.items():
        # Sanitize keys and values for LaTeX
        key_latex = str(key).replace('_', '\\_')
        value_latex = str(value).replace('_', '\\_')
        config_rows += f"\\textbf{{{key_latex}}} & {value_latex} \\\\\\\\ \n"

    # Sanitize filenames for use in LaTeX \includegraphics command
    forecast_plot_latex_path = os.path.basename(forecast_plot_filename)
    loss_plot_latex_path = os.path.basename(loss_plot_filename)


    # Define the LaTeX document template
    latex_template = f"""
\\documentclass{{article}}
\\usepackage{{graphicx}}
\\usepackage{{amsmath}}
\\usepackage{{geometry}}
\\usepackage{{listings}}
\\usepackage{{hyperref}}

\\geometry{{a4paper, margin=1in}}

\\title{{PINN Forecasting Report}}
\\author{{Generated on {datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}}}
\\date{{}}

\\begin{{document}}

\\maketitle

\\section*{{Run Summary}}
This report summarizes the results of a single run of the Physics-Informed Neural Network (PINN) for time series forecasting.

\\subsection*{{Run Configuration}}
\\begin{{table}}[h!]
\\centering
\\begin{{tabular}}{{|l|p{{0.6\\textwidth}}|}}
\\hline
\\textbf{{Parameter}} & \\textbf{{Value}} \\\\\\\\
\\hline
{config_rows}
\\hline
\\end{{tabular}}
\\caption{{Key configuration, hyperparameter, and script values for the run.}}
\\end{{table}}

\\subsection*{{Final Learned Parameters}}
\\begin{{table}}[h!]
\\centering
\\begin{{tabular}}{{|l|l|}}
\\hline
\\textbf{{Parameter}} & \\textbf{{Final Value}} \\\\\\\\
\\hline
{params_rows}
\\hline
\\end{{tabular}}
\\caption{{Final converged values of the learnable model parameters.}}\n
\\end{{table}}

\\clearpage

\\section*{{Visualizations}}

\\begin{{figure}}[h!]
\\centering
\\includegraphics[width=1.0\\textwidth]{{{forecast_plot_latex_path}}}
\\caption{{Forecast plot showing the model fit on training data and the forecast on the test set.}}
\\end{{figure}}

\\begin{{figure}}[h!]
\\centering
\\includegraphics[width=1.0\\textwidth]{{{loss_plot_latex_path}}}
\\caption{{Training loss over all epochs, displayed on a logarithmic scale.}}
\\end{{figure}}

\\clearpage

\\section*{{Full Log Output}}
This section contains the verbatim log output from the script execution for detailed analysis and debugging.

\\begin{{lstlisting}}[basicstyle=\\ttfamily\\small, breaklines=true]
{log_content}
\\end{{lstlisting}}

\\end{{document}}
    """

    # Write the content to the .tex file
    try:
        with open(report_filename, 'w', encoding='utf-8') as f:
            f.write(latex_template)
        print(f"Successfully generated LaTeX report: {report_filename}")
    except Exception as e:
        print(f"Error generating LaTeX report: {e}")


def zip_output_files(zip_filename, file_list):
    """
    Creates a zip file containing the specified list of files.

    Args:
        zip_filename (str): The name of the output zip file.
        file_list (list): A list of string paths to the files to be zipped.
    """
    try:
        with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for file in file_list:
                if os.path.exists(file):
                    zipf.write(file, os.path.basename(file))
                else:
                    print(f"Warning: File not found and will not be added to zip: {file}")
        print(f"Successfully created zip archive: {zip_filename}")
    except Exception as e:
        print(f"Error creating zip archive: {e}")